使用`python38`的环境，如果同时开了代理的话，`pip install`会报这个错误：

`after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /pypi/simple/pip/`



解决方法：

1. 临时关闭代理，打包完成后再重新打开；
2. 如果代理不能关，可以修改`%APPDATA%\pip\pip.ini`配置文件，添加一行`proxy=http://127.0.0.1:7890`到`global`配置下；



不过上面这个解决方法解决不了我要上传`pip`包到`pypi`的情况，经过一番搜索，我在知乎找到了答案：

[Python 遭遇 ProxyError 问题记录 - DavyCloud的文章 - 知乎](https://zhuanlan.zhihu.com/p/350015032)
分析得很清楚，其实和`Linux`那边一样设置`HTTP_PROXY`和`HTTPS_PROXY`的环境变量，全都设置为`http://127.0.0.1:xxxx`就行了，不过感觉就是不太舒服。